[tools]
argocd = "latest"
bat = "latest"
chezmoi = "latest"
fzf = "latest"
helm = "latest"
k3s = "latest"
k9s = "latest"
kubectl = "latest"
neovim = "latest"
yq = "latest"
zoxide = "latest"
eza = "latest"
starship = "latest"
node = "latest"
glow = "latest"
ripgrep = "latest"
btop = "latest"
